print('='*20, 'DESAFIO 7', '='*20)
print('')
print('Digite as 3 notas do aluno para saber sua media bimestral! ')
n1 = float(input('Primeira nota: '))
n2 = float(input('Segunda nota: '))
n3 = float(input('Teçeira nota: '))
print('')
print('Sua media bimestral é {:.1f}'.format((n1 + n2 + n3)/3))
