print('='*20, 'DESAFIO 3', '='*20)
print('')
n1 = int(input('Digite um número: '))
n2 = int(input('Digite outro número: '))
print('')
print('A soma entre {} e {} é igual a {}'.format(n1, n2, n1 + n2))
